services:
  dash:
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    networks:
      - proxy
    environment:
      DASHDOT_ENABLE_CPU_TEMPS: 'true'
    volumes:
      - /:/mnt/host:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashdot.entrypoints=http"
      - "traefik.http.routers.dashdot.rule=Host(`dashdot.local.EXAMPLE.com`)"
      - "traefik.http.middlewares.dashdot-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.dashdot.middlewares=dashdot-https-redirect"
      - "traefik.http.routers.dashdot-secure.entrypoints=https"
      - "traefik.http.routers.dashdot-secure.rule=Host(`dashdot.local.EXAMPLE.com`)"
      - "traefik.http.routers.dashdot-secure.tls=true"
      - "traefik.http.routers.dashdot-secure.service=dashdot"
      - "traefik.http.services.dashdot.loadbalancer.server.port=3001"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true